### ISSUE TITLE
Series Page

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#10]
### Value Proposition

As a **User** I need a **Series Page** to be able to **see the trailer, read information, and find the streams of the series that are available**

### Description

![Image](https://user-images.githubusercontent.com/100809251/210110479-930eed8d-a4cc-4dc2-a02f-36eb54be8202.png)

### Acceptance Criteria

- [x] the user should be able to see the trailer of the latest season
- [x] the social-media links should make the user to send the trailer to a friend
- [x] the image, name, year, and information of the latest season must be visible
- [x]  the layout should fit the sizes of the mobile devices
- [x] everything must be styled properly

### Tasks

(for developers team)

- [x] create a new branch
- [x] import the header and footer
- [x] add the trailer of the latest season 
- [x] add the icons as lists so that the user can send the trailer to a friend
- [x] add the image, name, year, and the information of the latest season
- [x] add the links of the streaming platforms
- [x] style everything using styled-components

### Sizing/Complexity

**L**

**Comment by DanielGennat** [comment]
same here. I think it's much more than L
