### ISSUE TITLE
Seach Bar

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#11]
### Value Proposition

**As a User I need a seach bar to be able to search the movies and series that I'm interested in.

### Description

<img width="383" alt="Screenshot 2022-11-29 at 14 28 22" src="https://user-images.githubusercontent.com/100809251/204541361-a5478e55-8ec2-4f55-bbce-040767e306b7.png">

<img width="287" alt="Screenshot 2022-11-29 at 14 53 04" src="https://user-images.githubusercontent.com/100809251/204547174-1bc7a416-d496-4666-9a63-642e3f3c162a.png">

### Acceptance Criteria

- [ ] the user must be able to search both movies and series
- [ ] the user's search must match the name of the movie/series
- [ ] when the user types the correct name of the movie/series it must be visible to his screen
- [ ] the output should be a link to the movie/series Page
- [ ] the layout should fit the sizes of the mobile devices

### Tasks

(for developers team)

- [ ] create a new branch
- [ ] match the value of the user's input with the names of the movies/series
- [ ] when the user's input match with a movie/series make it visible through a list of results

### Sizing/Complexity

**M**

**Comment by DanielGennat** [comment]
lgtm :)
