### ISSUE TITLE
# Footer

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#2]
### Value Proposition

As a User I need a navigation bar to be able to reach the owner if i have any issues.

### Description

<img width="475" alt="Screenshot 2022-11-28 at 14 30 25" src="https://user-images.githubusercontent.com/100809251/204290213-2cd1df7a-b4b3-4662-8eb8-91bb6721840c.png">

### Acceptance Criteria

- [x] the links work properly
- [x] the icons are visible
- [x] everything is styled 

### Tasks

(for developers team)

- [x] create a new branch 
- [x] add an Email, linkedIn, and Github icon so that when I click on it I can find the Owner
- [x] write the proper text  

### Sizing/Complexity

**S**
