### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#23]
### Value Proposition

As a **User** I want to **see a favicon** so that **i can easily find the browser tab of my page.**

### Acceptance Criteria

- [x] the page has a favicon

### Tasks

(for developers team)

- [x] create a favicon.ico
- [x]  convert to .ico
- [x]  implement in head of all pages

### Sizing/Complexity

**S**
