### ISSUE TITLE
Main Page Content

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#3]
### Value Proposition

As a User I need a main Page Content to be able to get recommendations for movies and series. Also to be able to send the website to my friends and colleagues

### Description

<img width="225" alt="Screenshot 2022-11-28 at 14 48 22" src="https://user-images.githubusercontent.com/100809251/204294299-8c63b906-7145-4d93-8f2d-3cb844d3a516.png">

### Acceptance Criteria

- [x] the photos are visible
- [x] the image of the movies and series are visible
- [x] the Name, year, and length of the Movie is visible
- [x] the Name, current Season & episodes of the newest Season must be visible.
- [x] everything is styled properly 

### Tasks

(for developers team)

- [x] create a new branch
- [x] find & add the photos
- [x] make the links work properly
- [x] style everything using styled-components.

### Sizing/Complexity

**M**
