### ISSUE TITLE
Sign In Page

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#4]
### Value Proposition

As a User I need a Log In Page so that I can Log In and be a part of the Family :)

### Description

<img width="235" alt="Screenshot 2022-11-28 at 16 37 59" src="https://user-images.githubusercontent.com/100809251/204318685-8f1f341b-4dd1-4403-a791-087b51082462.png">

### Acceptance Criteria

- [x] general layout should fit mobile page sizes
- [x] if any of the inputs are not valid the user should get an arror after clicking "Login
- [x] when the "Register" is clicked the user should visit the Registration Form
- [x] it is styled properly

### Tasks

(for developers team)

- [x] create a new branch
- [x] import the Header and Footer components
- [x] make the "Register" Link work
- [x] style the Log In Form using styled-components 

### Sizing/Complexity

**S**
