### ISSUE TITLE
Registration Form Page

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#5]
### Value Proposition

As a User I need a Registration Form Page in order to have the ability to become a part of this Website/Community :)

### Description

<img width="293" alt="Screenshot 2022-11-28 at 16 54 44" src="https://user-images.githubusercontent.com/100809251/204322615-7b195f3c-da8f-4559-a7b8-5935e68c8362.png">

### Acceptance Criteria

- [x] general layout should fit mobile page sizes
- [x] if the user types a wrong email address a paragraph is appeared:"something went wrong, please check out your email"
- [x] if the repeated password does not match with the first one, a paragraph is appeared: "something went wrong, make sure you type the same password as above"
- [x] the "Sign In" link must bring the user to the Log In Page.
- [x] it needs to be styled properly

### Tasks

(for developers team)

- [x] create a new Branch
- [x] import the Header and Footer components 
- [x] create the Gegistration Form
- [x] make the "Sign In" link
- [x] style it using styled-components

### Sizing/Complexity

**S**
