### ISSUE TITLE
Movie Page

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#6]
### Value Proposition

**As a User I need a movie Page so that I can search for movies of different genres 

### Description

<img width="157" alt="Screenshot 2022-11-29 at 10 42 10" src="https://user-images.githubusercontent.com/100809251/204495022-6e57dcbf-1a07-44a7-8735-c2df7ebe6838.png">

### Acceptance Criteria

- [x] the image or the movies are visible
- [x] the Name, year and number of minutes is visible
- [x] make every movie as a link to another page where the user can see the trailer, information, and the streams of the movie
- [x] everything is styled properly

### Tasks

(for developers team)

- [x] create a new branch
- [x] import the header and footer 
- [x] make the links work properly
- [x] style everything using styled-components

### Sizing/Complexity

**M**
