### ISSUE TITLE
Series Page

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#7]
### Value Proposition

As a User I need a Series Page so that I can search for series of different genres

### Description

<img width="158" alt="Screenshot 2022-11-29 at 10 56 37" src="https://user-images.githubusercontent.com/100809251/204497763-f8af1e82-4c45-4efe-a034-c0e8e87174e4.png">

### Acceptance Criteria

- [x] the images of the latest series are visible
- [x] the name, seasons, and episodes of the latest series are also visible
- [x] make every series as a link to another page where the user can see the trailer, information, and the streams of the latest series
- [x] everything is styled properly

### Tasks

(for developers team)

- [x] create a new branch
- [x] import the header and the footer
- [x] make the links work properly
- [x] style everything using styled-components

### Sizing/Complexity

**M**

**Comment by SirJohn42Walker** [comment]
Probably the same critique as with the last one, but this time I think you will be able to reuse much of the functionality of the movie page, so maybe this one really is an M.
