### ISSUE TITLE
Movie Page

### ISSUE THREAD

**Issue by Natrosvili** [Natrosvili/Capstone-Project-movies-series-app#9]
### Value Proposition

**As a User I need a movie page to be able to see the trailer, read information, and find the streams of the movie that are available

### Description

![Image](https://user-images.githubusercontent.com/100809251/210110147-9b942ed3-8544-443d-b18e-12a6f68efc72.png)

### Acceptance Criteria

- [x] user should be able to see the trailer of the movie
- [x] the image, name, year, and information of the movie must be visible
- [x] the layout should fit the sizes of the mobile devices 
- [x] everything must be styled properly

### Tasks

(for developers team)

- [x] create a new branch
- [x] import the header and footer
- [x] add the trailer of the movie
- [x] add the icons below the trailer
- [x] add the image, name, year, and the information of the movie 
- [x] add the links of the streaming platforms
- [x] style everything using styled-components

### Sizing/Complexity

**L**

**Comment by DanielGennat** [comment]
Hi Georgios,
nice user story but I think it's a very big one. I would rather split it up and start just embedding the trailer.

**Comment by Natrosvili** [comment]
> Hi Georgios, nice user story but I think it's a very big one. I would rather split it up and start just embedding the trailer.

Hello DanielGennat, 

Thank You for the Feedback! At the moment I'm going to leave it as it is until I reach these issues and when the time comes I will brake both the Movie and Series Page in smaller pieces.

Have a nice Evening 🌇.

**Comment by DanielGennat** [comment]
okay, happy coding :)
